# 心筋炎/心膜炎の報告一覧の表が掲載されているページを指定する設定ファイルです。
# 
#  name: ワクチンの名称
#  file: 情報抽出に使うPDFファイルのパス
#  pages: 情報を抽出する対象の表が掲載されているページ
#   例） 1,2,5ページを指定する場合  pages: '1,2,5'
#   例） 10ページから13ページを指定する場合  pages: '10-13'
#   例） 27ページ以降の全ページを指定する場合  pages: '27-end'
#  source: 使用するPDFが扱われている審議会の名称と、PDFのURL
#  script-version: 使用するextractスクリプトのバージョン
#
settings: [
  {
    name: 'コミナティRTU筋注（1価：オミクロン株XBB.1.5）',
    file: '001280774-myocarditis.csv',
    pages: '',
    source: {
      name: '第102回',
      url: 'https://www.mhlw.go.jp/content/10601000/001280774.pdf',
    },
    script-version: ex2
  },
  {
    name: 'コミナティRTU筋注（1価：オミクロン株XBB.1.5）',
    file: '001280774-pericarditis.csv',
    pages: '',
    source: {
      name: '第102回',
      url: 'https://www.mhlw.go.jp/content/10601000/001280774.pdf',
    },
    script-version: ex2
  },
]
