# 心筋炎/心膜炎の報告一覧の表が掲載されているページを指定する設定ファイルです。
#
#  実際にデータ抽出に使った設定のメモ用。
#

## コミナティ筋注
name: 'コミナティ筋注'
file_id: '001325489'
pages: '30-45'
symptoms: 'myocarditis'
count: '380'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001325489.pdf'
}

name: 'コミナティ筋注'
file_id: '001325489'
pages: '46-51'
symptoms: 'pericarditis'
count: '130'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001325489.pdf'
}

## コミナティ筋注5～11歳用
name: 'コミナティ筋注5～11歳用'
file_id: '001325499'
pages: '29'
symptoms: 'myocarditis'
count: '7'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001325499.pdf'
}

name: 'コミナティ筋注5～11歳用'
file_id: '001325499'
pages: '30'
symptoms: 'pericarditis'
count: '2'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001325499.pdf'
}

## スパイクバックス筋注
name: 'スパイクバックス筋注'
file_id: '001325490'
pages: '30-34'
symptoms: 'myocarditis'
count: '217'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001325490.pdf'
}

name: 'スパイクバックス筋注'
file_id: '001325490'
pages: '35-36'
symptoms: 'pericarditis'
count: '52'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001325490.pdf'
}

## ダイチロナ筋注（1価：オミクロン株XBB.1.5）
name: 'ダイチロナ筋注（1価：オミクロン株XBB.1.5）'
file_id: '001321075'
pages: '7'
symptoms: 'myocarditis'
count: '1'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001321075.pdf'
}

## コミナティ筋注（1価：オミクロン株XBB.1.5）
name: 'コミナティ筋注'
file_id: '001321070'
pages: '7'
symptoms: 'myocarditis'
count: '8'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001321070.pdf'
}

name: 'コミナティ筋注'
file_id: '001321070'
pages: '8'
symptoms: 'pericarditis'
count: '2'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001321070.pdf'
}

## コミナティ筋注5～11歳用（1価：オミクロン株XBB.1.5）
name: 'コミナティ筋注５～11歳用（１価：オミクロン株XBB.1.5）'
file_id: '001321073'
pages: '7'
symptoms: 'myocarditis'
count: '1'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001321073.pdf'
}

## スパイクバックス筋注 （1価：オミクロン株XBB.1.5）
name: 'スパイクバックス筋注 （1価：オミクロン株XBB.1.5）'
file_id: '001321071'
pages: '9'
symptoms: 'myocarditis'
count: '1'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001321071.pdf'
}

## ヌバキソビッド筋注
name: 'ヌバキソビッド筋注'
file_id: '001321072'
pages: '7'
symptoms: 'myocarditis'
count: '2'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001321072.pdf'
}