# 心筋炎/心膜炎の報告一覧の表が掲載されているページを指定する設定ファイルです。
# 
#  name: ワクチンの名称
#  file: 情報抽出に使うPDFファイルのパス
#  pages: 情報を抽出する対象の表が掲載されているページ
#   例） 1,2,5ページを指定する場合  pages: '1,2,5'
#   例） 10ページから13ページを指定する場合  pages: '10-13'
#   例） 27ページ以降の全ページを指定する場合  pages: '27-end'
#  source: 使用するPDFが扱われている審議会の名称と、PDFのURL
#  script-version: 使用するextractスクリプトのバージョン
#
settings: [
  {
    name: 'コミナティ筋注',
    file: '001198218-myocarditis-reports.csv',
    pages: '',
    source: {
      name: '第100回',
      url: 'https://www.mhlw.go.jp/content/10601000/001198218.pdf',
    },
    script-version: v2
  },
  {
    name: スパイクバックス筋注,
    file: ./pdf-files/001161442.pdf,
    pages: '29-end',
    source: {
      name: 第98回,
      url: https://www.mhlw.go.jp/content/10601000/001161442.pdf,
    },
    script-version: v1
  },
  # 001161443.pdfの35ページ目に記載の報告一覧は、正常に抽出ができない状態なので手作業で抽出する
  {
    name: コミナティ筋注5~11歳用,
    file: ./pdf-files/001161445.pdf,
    pages: '28-end',
    source: {
      name: 第98回,
      url: https://www.mhlw.go.jp/content/10601000/001161445.pdf,
    },
    script-version: v1
  },
]
