# 心筋炎/心膜炎の報告一覧の表が掲載されているページを指定する設定ファイルです。
#
#  実際にデータ抽出に使った設定のメモ用。
#

## 001325489
name: 'コミナティ筋注'
file_id: '001325489'
pages: '30-45'
symptoms: 'myocarditis'
count: '380'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001325489.pdf'
}

name: 'コミナティ筋注'
file_id: '001325489'
pages: '46-51'
symptoms: 'pericarditis'
count: '130'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001325489.pdf'
}

## 001325490
name: 'スパイクバックス筋注'
file_id: '001325490'
pages: '30-34'
symptoms: 'myocarditis'
count: '217'
source: {
  name: '第104回',
  url: 'https://www.mhlw.go.jp/content/11120000/001325490.pdf'
}

