settings: [
  {
    manufacturer: 'アストラゼネカ株式会社',
    name: 'バキスゼブリア筋注',
    file: '001011618.pdf',
    output: '001011618.json',
    pages: '3', # 1 issue
    script-version: v1
  },
  # コミナティ筋注は数が多いので何回かに分けてデータ抽出を行う。
  {
    manufacturer: 'ファイザー株式会社',
    name: 'コミナティ筋注',
    file: '001161432.pdf',
    output: '001161432-1.json',
    pages: '4-64',
    script-version: v1
  },
  {
    manufacturer: 'ファイザー株式会社',
    name: 'コミナティ筋注',
    file: '001161432.pdf',
    output: '001161432-2.json',
    pages: '65-130',
    script-version: v1
  },
  {
    manufacturer: 'ファイザー株式会社',
    name: 'コミナティ筋注',
    file: '001161432.pdf',
    output: '001161432-3.json',
    pages: '131-200',
    script-version: v1
  },
  {
    manufacturer: 'ファイザー株式会社',
    name: 'コミナティ筋注',
    file: '001161432.pdf',
    output: '001161432-4.json',
    pages: '201-260',
    script-version: v1
  },
  {
    manufacturer: 'ファイザー株式会社',
    name: 'コミナティ筋注',
    file: '001161432.pdf',
    output: '001161432-5.json',
    # No. 1684, 1810の年齢は取り消し線で消している箇所があり、手動で修正が必要
    pages: '261-299',
    script-version: v1
  },
  {
    manufacturer: 'ファイザー株式会社',
    name: 'コミナティRTU筋注（2価:起源株/オミクロン株BA.1）',
    file: '001161432.pdf',
    output: '001161432-6.json',
    pages: '300-302',
    script-version: v1
  },
  {
    manufacturer: 'ファイザー株式会社',
    name: 'コミナティRTU筋注（2価:起源株/オミクロン株BA.4-5）',
    file: '001161432.pdf',
    output: '001161432-7.json',
    # No. 41の年齢は取り消し線で消している箇所があり、手動で修正が必要
    pages: '303-333',
    script-version: v1
  },
  {
    manufacturer: 'モデルナ・ジャパン株式会社',
    name: 'スパイクバックス筋注',
    file: '001161434.pdf',
    output: '001161434-1.json',
    pages: '4-49',
    script-version: v1
  },
  {
    manufacturer: 'モデルナ・ジャパン株式会社',
    name: 'スパイクバックス筋注（2価:起源株/オミクロン株BA.1）',
    file: '001161434.pdf',
    output: '001161434-2.json',
    pages: '50-51',
    script-version: v1
  },
  {
    manufacturer: 'モデルナ・ジャパン株式会社',
    name: 'スパイクバックス筋注（2価:起源株/オミクロン株BA.4-5）',
    file: '001161434.pdf',
    output: '001161434-3.json',
    pages: '52-53',
    script-version: v1
  },
  {
    manufacturer: '武田薬品工業株式会社',
    name: 'ヌバキソビッド筋注',
    file: '001161437.pdf',
    output: '001161437.json',
    pages: '3-4',
    script-version: v1
  },
  {
    manufacturer: 'ファイザー株式会社',
    name: コミナティ筋注5～11歳用,
    file: '001161438.pdf',
    output: '001161438.json',
    pages: '3-5',
    script-version: v1
  },
  {
    manufacturer: 'ファイザー株式会社',
    name: 'コミナティ筋注6ヵ月～4歳用',
    file: '001161440.pdf',
    output: '001161440.json',
    pages: '3',
    script-version: v1
  }
]