settings: [
  {
    name: 'バキスゼブリア筋注',
    file: '001011618.pdf',
    pages: '1',
    script-version: v1
  },
  {
    name: 'コミナティ筋注',
    file: '001197737.pdf',
    pages: '1',
    script-version: v1
  },
  {
    name: 'スパイクバックス筋注',
    file: '001197738.pdf',
    pages: '1',
    script-version: v1
  },
  {
    name: 'ヌバキソビッド筋注',
    file: '001197905.pdf',
    pages: '1',
    script-version: v1
  },
  {
    name: 'コミナティ筋注5～11歳用',
    file: '001161438.pdf',
    pages: '1',
    script-version: v1
  },
  {
    name: 'コミナティ筋注6ヵ月～4歳用',
    file: '001161440.pdf',
    pages: '1',
    script-version: v1
  },
  {
    name: 'コミナティRTU筋注（1価:オミクロン株XBB.1.5）',
    file: '001245072.pdf',
    pages: '1',
    script-version: v1
  },
  {
    name: 'スパイクバックス筋注（1価:オミクロン株XBB.1.5）',
    file: '001244792.pdf',
    pages: '1',
    script-version: v2
  },
  # 001197008.pdfは報告なしのため、手作りでjsonを作成した
  # 001197009.pdfも上記と同様。
]