settings: [
  {
    name: バキスゼブリア筋注,
    file: ./pdf-files/001011618.pdf,
    pages: '1',
    script-version: v1
  },
  {
    name: コミナティ筋注,
    file: ./pdf-files/001161432.pdf,
    pages: '1',
    script-version: v1
  },
  {
    name: スパイクバックス筋注,
    file: ./pdf-files/001161434.pdf,
    pages: '1',
    script-version: v1
  },
  {
    name: ヌバキソビッド筋注,
    file: ./pdf-files/001161437.pdf,
    pages: '1',
    script-version: v1
  },
  {
    name: コミナティ筋注5～11歳用,
    file: ./pdf-files/001161438.pdf,
    pages: '1',
    script-version: v1
  },
  {
    name: コミナティ筋注6ヵ月～4歳用,
    file: ./pdf-files/001161440.pdf,
    pages: '1',
    script-version: v1
  }
]