settings: [
  {
    file: '102nd/001280751.csv',
    output: '001280751.json',
    pages: '2',
    expected_count: 1,
    source: {
      name: 第102回,
      url: https://www.mhlw.go.jp/content/10601000/001280751.pdf
    },
    script-version: ex1
  }
]
