settings: [
  # 001197722 は0件のため抽出なし
  # 001198858 も同様
  {
    file: '100th/001198859.pdf',
    output: '001198859.json',
    pages: '2',
    expected_count: 13,
    source: {
      name: 第100回,
      url: https://www.mhlw.go.jp/content/10601000/001198859.pdf
    },
    script-version: v2
  }
]
