settings: [
  {
    file: '101st/001244773.pdf',
    output: '001244773.json',
    pages: '2',
    expected_count: 1,
    source: {
      name: 第101回,
      url: https://www.mhlw.go.jp/content/10601000/001244773.pdf
    },
    script-version: v2
  }
]
